version: "3.7"
services:
  database:
    container_name: sqlite3
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
       SA_PASSWORD: "Sid_database"
       ACCEPT_EULA: "Y"
  
  tracker-service:
    build: ./
    ports:
      - "3000:5000"
  
   





